openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for watchlist
paths:
    /watchlist:
        get:
            tags:
                - watchlist
            summary: getWatchlist watchlist
            operationId: watchlist#getWatchlist
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Watchlist'
                            example:
                                tickers:
                                    - ohlcv:
                                        change: 20
                                        change_percent: 13.33
                                        close: 170
                                        high: 200
                                        last_updated_at: 1768744190
                                        low: 50
                                        open: 150
                                        volume: 1000000
                                      ticker:
                                        exchange_mic: XNAS
                                        name: Apple Inc
                                        symbol: AAPL
                                    - ohlcv:
                                        change: 20
                                        change_percent: 13.33
                                        close: 170
                                        high: 200
                                        last_updated_at: 1768744190
                                        low: 50
                                        open: 150
                                        volume: 1000000
                                      ticker:
                                        exchange_mic: XNAS
                                        name: Apple Inc
                                        symbol: AAPL
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ratione praesentium est beatae officiis.
                            example: Distinctio et quo.
                "403":
                    description: 'permission_denied: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Laboriosam vel.
                            example: Et quia veritatis.
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ut voluptate porro aliquid quos voluptate eaque.
                            example: Ea veritatis magni pariatur.
                "502":
                    description: 'upstream_error: Bad Gateway response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Officiis nisi ut.
                            example: Et culpa officiis ea ex placeat.
                "503":
                    description: 'database_unavailable: Service Unavailable response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Est maxime nam rem culpa.
                            example: Reiciendis quia eum quasi.
    /watchlist/{symbol}:
        delete:
            tags:
                - watchlist
            summary: removeWatchlistTicker watchlist
            operationId: watchlist#removeWatchlistTicker
            parameters:
                - name: symbol
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Enim id sed vitae.
                  example: Autem quasi eum.
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Iure consequatur libero molestiae vel.
                            example: Quibusdam et eius dignissimos.
                "403":
                    description: 'permission_denied: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Et nobis aut omnis sit deleniti.
                            example: Voluptas fuga non.
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ipsum cum mollitia.
                            example: Repellendus ex sed quaerat a ullam et.
                "409":
                    description: 'database_record_locked: Conflict response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ea expedita vel dolores sit.
                            example: Sequi et repudiandae voluptas.
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Qui minus et provident.
                            example: Sunt modi et perferendis cupiditate modi tempore.
                "502":
                    description: 'upstream_error: Bad Gateway response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Enim soluta minima impedit ratione ratione voluptate.
                            example: Unde laboriosam omnis voluptatem aut.
                "503":
                    description: 'database_unavailable: Service Unavailable response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Nihil quia sed est consectetur dolorum a.
                            example: Aperiam rerum molestiae totam.
    /watchlist/ticker:
        post:
            tags:
                - watchlist
            summary: addWatchlistTicker watchlist
            operationId: watchlist#addWatchlistTicker
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Ticker'
                        example:
                            exchange_mic: XNAS
                            name: Apple Inc
                            symbol: AAPL
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TickerItem'
                            example:
                                ohlcv:
                                    change: 20
                                    change_percent: 13.33
                                    close: 170
                                    high: 200
                                    last_updated_at: 1768744190
                                    low: 50
                                    open: 150
                                    volume: 1000000
                                ticker:
                                    exchange_mic: XNAS
                                    name: Apple Inc
                                    symbol: AAPL
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quia aspernatur voluptas.
                            example: Est exercitationem repudiandae autem libero.
                "403":
                    description: 'permission_denied: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Suscipit quod.
                            example: Et rerum est quia optio quam.
                "409":
                    description: 'ticker_already_exists: Conflict response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ut eos deserunt autem voluptas quo repellendus.
                            example: Aut nam iste distinctio.
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Vel assumenda expedita consectetur aut.
                            example: Nobis qui qui fugiat.
                "502":
                    description: 'upstream_error: Bad Gateway response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Debitis velit.
                            example: Distinctio quas.
                "503":
                    description: 'database_unavailable: Service Unavailable response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ratione distinctio corrupti.
                            example: Ut neque molestiae.
components:
    schemas:
        OHLCV:
            type: object
            properties:
                change:
                    type: number
                    description: Price Change
                    example: 20
                    format: double
                change_percent:
                    type: number
                    description: Price Change Percent
                    example: 13.33
                    format: double
                close:
                    type: number
                    description: Close Price
                    example: 170
                    format: double
                high:
                    type: number
                    description: High Price
                    example: 200
                    format: double
                last_updated_at:
                    type: integer
                    description: Last Update Timestamp (Unix)
                    example: 1768744190
                    format: int64
                low:
                    type: number
                    description: Low Price
                    example: 50
                    format: double
                open:
                    type: number
                    description: Open Price
                    example: 150
                    format: double
                volume:
                    type: number
                    description: Volume
                    example: 1000000
                    format: double
            example:
                change: 20
                change_percent: 13.33
                close: 170
                high: 200
                last_updated_at: 1768744190
                low: 50
                open: 150
                volume: 1000000
            required:
                - open
                - high
                - low
                - close
                - volume
                - change
                - change_percent
                - last_updated_at
        Ticker:
            type: object
            properties:
                exchange_mic:
                    type: string
                    description: Exchange MIC Code
                    example: XNAS
                name:
                    type: string
                    description: Stock Name
                    example: Apple Inc
                symbol:
                    type: string
                    description: Stock Symbol
                    example: AAPL
            example:
                exchange_mic: XNAS
                name: Apple Inc
                symbol: AAPL
            required:
                - symbol
        TickerItem:
            type: object
            properties:
                ohlcv:
                    $ref: '#/components/schemas/OHLCV'
                ticker:
                    $ref: '#/components/schemas/Ticker'
            example:
                ohlcv:
                    change: 20
                    change_percent: 13.33
                    close: 170
                    high: 200
                    last_updated_at: 1768744190
                    low: 50
                    open: 150
                    volume: 1000000
                ticker:
                    exchange_mic: XNAS
                    name: Apple Inc
                    symbol: AAPL
            required:
                - ticker
                - ohlcv
        Watchlist:
            type: object
            properties:
                tickers:
                    type: array
                    items:
                        $ref: '#/components/schemas/TickerItem'
                    example:
                        - ohlcv:
                            change: 20
                            change_percent: 13.33
                            close: 170
                            high: 200
                            last_updated_at: 1768744190
                            low: 50
                            open: 150
                            volume: 1000000
                          ticker:
                            exchange_mic: XNAS
                            name: Apple Inc
                            symbol: AAPL
                        - ohlcv:
                            change: 20
                            change_percent: 13.33
                            close: 170
                            high: 200
                            last_updated_at: 1768744190
                            low: 50
                            open: 150
                            volume: 1000000
                          ticker:
                            exchange_mic: XNAS
                            name: Apple Inc
                            symbol: AAPL
                        - ohlcv:
                            change: 20
                            change_percent: 13.33
                            close: 170
                            high: 200
                            last_updated_at: 1768744190
                            low: 50
                            open: 150
                            volume: 1000000
                          ticker:
                            exchange_mic: XNAS
                            name: Apple Inc
                            symbol: AAPL
            example:
                tickers:
                    - ohlcv:
                        change: 20
                        change_percent: 13.33
                        close: 170
                        high: 200
                        last_updated_at: 1768744190
                        low: 50
                        open: 150
                        volume: 1000000
                      ticker:
                        exchange_mic: XNAS
                        name: Apple Inc
                        symbol: AAPL
                    - ohlcv:
                        change: 20
                        change_percent: 13.33
                        close: 170
                        high: 200
                        last_updated_at: 1768744190
                        low: 50
                        open: 150
                        volume: 1000000
                      ticker:
                        exchange_mic: XNAS
                        name: Apple Inc
                        symbol: AAPL
                    - ohlcv:
                        change: 20
                        change_percent: 13.33
                        close: 170
                        high: 200
                        last_updated_at: 1768744190
                        low: 50
                        open: 150
                        volume: 1000000
                      ticker:
                        exchange_mic: XNAS
                        name: Apple Inc
                        symbol: AAPL
            required:
                - tickers
tags:
    - name: watchlist
      description: Manage user watchlist
